version: "3.4"

services:
    api:
        build:
            context: ./src/
            network: host
            dockerfile: Dockerfile
        container_name: status-server
        restart: unless-stopped
        ports:
            - 5000:5000
        environment:
            TZ: "Asia/Singapore"
            PORT: "5000"
            MODULE_NAME: "api.server.main"
            LOG_LEVEL: "debug"
            PRE_START_PATH: "/app/api/server/prestart.sh"
            # Gunicorn workers
            MAX_WORKERS: "2"
        volumes:
            - "./logs:/app/logs"
